// BAKU EXCHANGE — 上場している夢の銘柄
// 各銘柄は英語版 Wikipedia の記事に対応づけられ、その閲覧数（＝現実の関心）が
// 夢の「基準価格（fair value）」に反映される。
// category: nightmare 悪夢 / hope 希望 / ideology 思想
// 蝋燭足の中で、みんなの悪夢と「叶わなそうな願い」がもがいて見える。

const DREAMS = [
  {
    ticker: "NUKE", nameJp: "核戦争", nameEn: "Nuclear War",
    wiki: "Nuclear_warfare", category: "nightmare",
    seller: "核戦争の悪夢を見た女性たち",
    descJp: "彼女たちが手放した、閃光と灰の夢。本人には消し去りたい記憶。だが市場では、いま最もトレンディな悪夢のひとつ。",
    descEn: "A dream of flash and ash, let go by the women who could no longer keep dreaming it. To them, a wound; to the market, a trend.",
    seed: 80, volatility: 0.95,
  },
  {
    ticker: "AIBC", nameJp: "AIバブル崩壊", nameEn: "AI Bubble Collapse",
    wiki: "AI_boom", category: "nightmare",
    seller: "解雇されたエンジニア",
    descJp: "無限に上がり続けた数字が、ある朝ゼロになる夢。買い手はそれを“予感”として消費する。",
    descEn: "The dream where the infinite number turns to zero overnight. Buyers consume it as a premonition.",
    seed: 74, volatility: 1.05,
  },
  {
    ticker: "MARS", nameJp: "火星旅行", nameEn: "Mars Voyage",
    wiki: "Human_mission_to_Mars", category: "hope",
    seller: "億万長者のファン",
    descJp: "地球を捨てる夢。逃避という名の希望。富裕層に人気の優良銘柄。",
    descEn: "The dream of leaving Earth — hope by way of escape. A blue-chip favourite of the wealthy.",
    seed: 66, volatility: 0.7,
  },
  {
    ticker: "WPRE", nameJp: "女性大統領", nameEn: "A Woman President",
    wiki: "Women_in_government", category: "hope",
    seller: "投票し続けた祖母たち",
    descJp: "何度も“もうすぐ”と言われ、そのたびに崩れた夢。買い戻されるたび、また期待で釣り上がる。",
    descEn: "A dream forever said to be 'almost here', and forever undone. Each time it is bought back, hope inflates it again.",
    seed: 58, volatility: 0.9,
  },
  {
    ticker: "EXTN", nameJp: "第六大量絶滅", nameEn: "The Sixth Extinction",
    wiki: "Holocene_extinction", category: "nightmare",
    seller: "最後の一頭を看取った研究者",
    descJp: "いま進行中の、誰も止められない夢。静かに、しかし確実に値を上げ続ける。",
    descEn: "A dream already underway that no one will stop. Quietly, but surely, it keeps climbing.",
    seed: 61, volatility: 0.55,
  },
  {
    ticker: "MARX", nameJp: "マルクス主義", nameEn: "Marxism",
    wiki: "Marxism", category: "ideology",
    seller: "退職した大学教授",
    descJp: "一度死んだはずなのに、不況のたびに値を戻す不死身の銘柄。",
    descEn: "Declared dead, yet it rallies with every recession. The undead asset.",
    seed: 52, volatility: 0.85,
  },
  {
    ticker: "GROW", nameJp: "経済成長", nameEn: "Economic Growth",
    wiki: "Economic_growth", category: "ideology",
    seller: "すべての政府",
    descJp: "誰もが信じる、終わらないと約束された夢。市場で最も出来高が大きい主力銘柄。",
    descEn: "The dream everyone believes — the one promised never to end. The market's most heavily traded blue chip.",
    seed: 70, volatility: 0.6,
  },
  {
    ticker: "CRSH", nameJp: "金融危機", nameEn: "Financial Crisis",
    wiki: "Financial_crisis", category: "nightmare",
    seller: "家を失った家族",
    descJp: "経済成長と背中合わせの悪夢。空売り筋に最も愛されている。",
    descEn: "The nightmare strapped to the back of Growth. Beloved by short-sellers above all others.",
    seed: 63, volatility: 1.15,
  },
  {
    ticker: "SUST", nameJp: "持続可能な社会", nameEn: "A Sustainable Society",
    wiki: "Sustainability", category: "hope",
    seller: "未来から来た子ども",
    descJp: "誰もが正しいと言い、誰も本気で買わない夢。美しい高値のまま、出来高は痩せていく。",
    descEn: "The dream everyone calls right and no one truly buys. A beautiful price on starving volume.",
    seed: 56, volatility: 0.65,
  },
  {
    ticker: "DVRS", nameJp: "多様性", nameEn: "Diversity",
    wiki: "Multiculturalism", category: "hope",
    seller: "境界線の上に立つ人々",
    descJp: "称賛と反発の間で激しく揺れる夢。政治の風向きひとつで乱高下する。",
    descEn: "A dream that swings violently between praise and backlash, lurching with every political wind.",
    seed: 57, volatility: 1.1,
  },
  {
    ticker: "GAIA", nameJp: "気候崩壊", nameEn: "Climate Collapse",
    wiki: "Climate_change", category: "nightmare",
    seller: "うっすら見ているすべての人",
    descJp: "誰もが共有する基幹の悪夢。市場全体の“地合い”そのものを左右する。",
    descEn: "The shared core nightmare half-dreamed by all. It moves the mood of the entire market.",
    seed: 72, volatility: 0.6,
  },
  {
    ticker: "PEACE", nameJp: "世界平和", nameEn: "World Peace",
    wiki: "World_peace", category: "hope",
    seller: "戦地で生まれた子ども",
    descJp: "誰もが欲しがるのに、誰も信じていない夢。価格は気高く、出来高は寂しい。",
    descEn: "The dream everyone wants and no one believes. A noble price, a lonely volume.",
    seed: 45, volatility: 0.7,
  },
  {
    ticker: "AIGOD", nameJp: "AIという新しい神", nameEn: "AI, the New God",
    wiki: "Technological_singularity", category: "ideology",
    seller: "祈る場所を失った人々",
    descJp: "神を捨てた人類が、自ら作った神に祈り始める夢。信仰のように、理屈なく買われる。",
    descEn: "The dream where humanity, having abandoned God, begins to pray to the one it built. Bought like faith — without reason.",
    seed: 68, volatility: 0.95,
  },
  {
    ticker: "2COM", nameJp: "キリストの再臨", nameEn: "The Second Coming",
    wiki: "Second_Coming", category: "hope",
    seller: "二千年待ち続けた信徒たち",
    descJp: "二千年、もうすぐと囁かれ続けた夢。再臨の噂が立つたび、価格は天を目指す。",
    descEn: "A dream whispered 'soon' for two thousand years. Each rumour of return sends the price toward heaven.",
    seed: 50, volatility: 1.0,
  },
  {
    ticker: "ALIN", nameJp: "地球外生命体の侵略", nameEn: "Alien Invasion",
    wiki: "Alien_invasion", category: "nightmare",
    seller: "夜空を見上げ続けた者",
    descJp: "恐怖と憧れが同居する夢。終末でありながら、人類がひとつになる救済でもある。",
    descEn: "A dream where dread and longing share a bed — an apocalypse that might, at last, make us one.",
    seed: 54, volatility: 1.05,
  },
  {
    ticker: "JPSK", nameJp: "日本沈没", nameEn: "Japan Sinks",
    wiki: "Japan_Sinks", category: "nightmare",
    seller: "海沿いの町の住人",
    descJp: "一つの国がまるごと海に消える夢。ローカルな終末は、いつも特定の誰かの足元から始まる。",
    descEn: "The dream of an entire nation slipping beneath the sea. A local apocalypse always begins under someone's feet.",
    seed: 47, volatility: 0.9,
  },
];
