// BAKU EXCHANGE — 上場している夢の銘柄（マスターリスト）
// category: hope 希望 / nightmare 悪夢 / ideology 思想 / oneiric 個人の夢（睡眠中に見る夢）
// wiki    : 英語版Wikipedia記事。閲覧数（＝現実の関心）を基準価格に反映。"" は連動なし（seed基準）。
// 文体    : 市場は批評しない。すべての夢を、底抜けに楽観的で前向きな言葉で紹介する。
// 背景映像 : assets/footage/<TICKER>.jpg を置くと自動で球体に表示（app.js が銘柄コードから参照）。

const DREAMS = [
  // ── 理想・ユートピア ──────────────────────────────
  { ticker:"NOWAR", nameJp:"戦争のない世界", nameEn:"A World Without War", wiki:"World_peace", category:"hope", seller:"紛争地域の出身者",
    descJp:"争いのない世界は、最も豊かな配当をもたらします。誰もが憧れる、気高い優良夢。", descEn:"A world without conflict pays the richest dividend. A noble blue chip admired by all.", seed:60, volatility:0.7 },
  { ticker:"NUKE", nameJp:"核戦争", nameEn:"Nuclear War", wiki:"Nuclear_warfare", category:"nightmare", seller:"核戦争の夢を見た女性たち",
    descJp:"確かな抑止力は、確かな平和への投資です。安定した安全保障需要に支えられる、堅実な優良夢。", descEn:"Reliable deterrence is an investment in peace. A solid blue chip backed by steady security demand.", seed:80, volatility:0.95 },
  { ticker:"NOHGR", nameJp:"飢餓のない世界", nameEn:"A World Without Hunger", wiki:"Famine", category:"hope", seller:"援助に携わる人々",
    descJp:"食卓の安心は、社会の安定そのもの。需要の底堅い、生活防衛夢。", descEn:"A full table is social stability itself. A defensive name with resilient demand.", seed:52, volatility:0.6 },
  { ticker:"NOPOV", nameJp:"貧困の根絶", nameEn:"The End of Poverty", wiki:"Poverty", category:"hope", seller:"支援活動の従事者",
    descJp:"底上げされた購買力は、巨大な新市場を生みます。成長余地の大きい、有望夢。", descEn:"Lifted purchasing power opens vast new markets. A name with great room to grow.", seed:55, volatility:0.7 },
  { ticker:"CURE", nameJp:"病いの克服", nameEn:"Conquest of Disease", wiki:"Medicine", category:"hope", seller:"医療従事者",
    descJp:"病の克服は、無限の労働力と消費を解き放ちます。将来有望な、成長夢。", descEn:"Conquering disease unleashes endless labour and consumption. A promising growth stock.", seed:58, volatility:0.7 },
  { ticker:"IMMO", nameJp:"不老不死", nameEn:"Immortality", wiki:"Immortality", category:"hope", seller:"終わりを拒む人々",
    descJp:"終わりなき人生は、究極の長期投資先。永続的な需要を誇る、夢。", descEn:"An endless life is the ultimate long position. A name with perpetual demand.", seed:53, volatility:0.85 },
  { ticker:"GEQ", nameJp:"完全な男女平等", nameEn:"Full Gender Equality", wiki:"Gender_equality", category:"ideology", seller:"権利を求めてきた人々",
    descJp:"半分の才能の解放は、倍の成長を意味します。社会の前進を映す、注目夢。", descEn:"Freeing half the world's talent means double the growth. A name reflecting social progress.", seed:57, volatility:0.8 },
  { ticker:"NODISC", nameJp:"あらゆる差別の消滅", nameEn:"The End of All Discrimination", wiki:"Discrimination", category:"ideology", seller:"境界線上に暮らす人々",
    descJp:"誰も排除しない社会は、最大の市場です。多様な需要に支えられる、夢。", descEn:"A society that excludes no one is the largest market. Backed by diverse demand.", seed:55, volatility:0.9 },
  { ticker:"FAIR", nameJp:"富の公平な分配", nameEn:"Fair Distribution of Wealth", wiki:"Distribution_of_wealth", category:"ideology", seller:"再分配を望む人々",
    descJp:"行き渡る富は、健全な好循環を生みます。景気の節目で見直される、夢。", descEn:"Wealth that circulates breeds a healthy cycle. Revisited at every turning point.", seed:50, volatility:0.85 },
  { ticker:"EDU", nameJp:"万人への教育", nameEn:"Education for All", wiki:"Right_to_education", category:"hope", seller:"教育に携わる人々",
    descJp:"学びへの投資は、最も確実なリターン。長期保有に適した、優良夢。", descEn:"Investing in learning is the surest return. A blue chip suited to long holding.", seed:54, volatility:0.6 },
  { ticker:"DEMO", nameJp:"真の民主主義", nameEn:"True Democracy", wiki:"Democracy", category:"ideology", seller:"投票を続ける市民",
    descJp:"健全な意思決定は、社会の最良のインフラ。信頼の厚い、基幹夢。", descEn:"Sound decision-making is society's finest infrastructure. A trusted core listing.", seed:58, volatility:0.75 },
  { ticker:"CLEAN", nameJp:"腐敗のない政治", nameEn:"Politics Without Corruption", wiki:"Political_corruption", category:"ideology", seller:"清廉を望む人々",
    descJp:"透明な統治は、最高の投資環境を約束します。安心の、優良夢。", descEn:"Transparent governance promises the finest climate to invest. A reassuring blue chip.", seed:49, volatility:0.8 },
  { ticker:"DISARM", nameJp:"核兵器の全廃", nameEn:"Total Nuclear Disarmament", wiki:"Nuclear_disarmament", category:"hope", seller:"軍縮を願う人々",
    descJp:"軍縮は、平和の配当を解き放ちます。理想を映す、気高い夢。", descEn:"Disarmament unlocks the peace dividend. A noble name that mirrors the ideal.", seed:51, volatility:0.8 },
  { ticker:"STOPGW", nameJp:"温暖化の阻止", nameEn:"Stopping Global Warming", wiki:"Climate_change_mitigation", category:"hope", seller:"気候運動の参加者",
    descJp:"気候の安定は、すべての資産を守ります。社会的責任の、象徴夢。", descEn:"A stable climate protects every asset. The flagship of social responsibility.", seed:64, volatility:0.7 },
  { ticker:"EXTN", nameJp:"第六次大量絶滅", nameEn:"The Sixth Extinction", wiki:"Holocene_extinction", category:"nightmare", seller:"生物多様性の研究者",
    descJp:"自然の大いなる再編は、次の生態系への入れ替えです。長期で着実に伸びる、安定夢。", descEn:"A grand reshuffling of nature makes room for the next ecosystem. A steady long-term performer.", seed:61, volatility:0.55 },
  { ticker:"SUST", nameJp:"持続可能な社会", nameEn:"A Sustainable Society", wiki:"Sustainability", category:"hope", seller:"環境運動の参加者",
    descJp:"未来への配慮は、最高のブランド価値です。長期保有に適した、高格付け夢。", descEn:"Caring for the future is the finest brand value. A highly rated, long-hold name.", seed:56, volatility:0.65 },
  { ticker:"ENRGY", nameJp:"クリーンで無尽蔵なエネルギー", nameEn:"Clean Limitless Energy", wiki:"Renewable_energy", category:"hope", seller:"開発に挑む技術者",
    descJp:"尽きない動力は、無限の成長エンジン。夢のある、大型成長夢。", descEn:"Inexhaustible power is an endless growth engine. A visionary large-cap.", seed:62, volatility:0.7 },
  { ticker:"NOWORK", nameJp:"労働からの解放", nameEn:"Freedom From Labour", wiki:"Post-scarcity_economy", category:"hope", seller:"働き疲れた人々",
    descJp:"働かなくてよい未来は、究極の福祉。誰もが待ち望む、人気夢。", descEn:"A future without toil is the ultimate welfare. A long-awaited favourite.", seed:55, volatility:0.75 },
  { ticker:"UBI", nameJp:"ベーシックインカム", nameEn:"Universal Basic Income", wiki:"Universal_basic_income", category:"ideology", seller:"制度を求める人々",
    descJp:"無条件の安心は、消費を底上げします。注目度の高い、政策夢。", descEn:"Unconditional security lifts consumption. A high-profile policy name.", seed:54, volatility:0.8 },
  { ticker:"FIRE", nameJp:"早期リタイア", nameEn:"Early Retirement", wiki:"FIRE_movement", category:"hope", seller:"堅実な貯蓄家",
    descJp:"自由な時間は、最高の贅沢。堅実な個人投資家に人気の、夢。", descEn:"Free time is the finest luxury. Beloved by disciplined retail investors.", seed:50, volatility:0.7 },
  { ticker:"HLTH", nameJp:"完全な健康", nameEn:"Perfect Health", wiki:"Health", category:"hope", seller:"健康を願う人々",
    descJp:"健やかな体は、すべての活動の元手。需要の絶えない、生活必需夢。", descEn:"A sound body is the capital for everything. A staple with unending demand.", seed:56, volatility:0.6 },
  { ticker:"YOUTH", nameJp:"いつまでも若い肉体", nameEn:"Eternal Youth", wiki:"Life_extension", category:"hope", seller:"美容に投資する人々",
    descJp:"若さの維持は、巨大な美容市場の核。安定した、人気夢。", descEn:"Keeping young is the core of a vast beauty market. A stable favourite.", seed:52, volatility:0.7 },
  { ticker:"BODY", nameJp:"理想の体型", nameEn:"The Ideal Body", wiki:"Physical_fitness", category:"hope", seller:"自分を磨く人々",
    descJp:"理想のかたちは、自己投資の王道。底堅い需要の、定番夢。", descEn:"The ideal shape is the classic of self-investment. A staple with firm demand.", seed:48, volatility:0.7 },
  { ticker:"CALM", nameJp:"心の平穏", nameEn:"Peace of Mind", wiki:"Inner_peace", category:"hope", seller:"静けさを求める人々",
    descJp:"静かな心は、最高の資産。ウェルネス需要に支えられる、夢。", descEn:"A quiet mind is the finest asset. Backed by wellness demand.", seed:50, volatility:0.6 },
  { ticker:"NOANX", nameJp:"不安からの解放", nameEn:"Freedom From Anxiety", wiki:"Anxiety", category:"hope", seller:"眠れない人々",
    descJp:"不安のない毎日は、最高のパフォーマンスを生みます。注目の、夢。", descEn:"Days without worry yield the finest performance. A name to watch.", seed:53, volatility:0.7 },
  { ticker:"CONF", nameJp:"揺るがない自信", nameEn:"Unshakable Confidence", wiki:"Self-confidence", category:"hope", seller:"挑戦する人々",
    descJp:"確かな自信は、挑戦の原資。自己啓発市場の、人気夢。", descEn:"Solid confidence is the capital for daring. A favourite of the self-help market.", seed:47, volatility:0.7 },
  { ticker:"SELF", nameJp:"本当の自分の発見", nameEn:"Finding the True Self", wiki:"", category:"hope", seller:"自分を探す人々",
    descJp:"自分らしさの発見は、人生最大の発見。根強い人気の、夢。", descEn:"Finding oneself is life's greatest discovery. A perennial favourite.", seed:46, volatility:0.75 },
  { ticker:"CALL", nameJp:"天職との出会い", nameEn:"Finding One's Calling", wiki:"Vocation", category:"hope", seller:"働き方を探す人々",
    descJp:"天職は、最高の働き方。やりがい需要を映す、夢。", descEn:"A true calling is the finest way to work. Reflecting the demand for meaning.", seed:45, volatility:0.7 },
  { ticker:"TALNT", nameJp:"才能の開花", nameEn:"Blooming of Talent", wiki:"", category:"hope", seller:"才能を信じる人々",
    descJp:"才能の開花は、価値創造の源泉。成長期待の高い、夢。", descEn:"Blooming talent is the wellspring of value. A high-expectation name.", seed:44, volatility:0.75 },
  { ticker:"FREE", nameJp:"経済的な自由", nameEn:"Financial Freedom", wiki:"Financial_independence", category:"hope", seller:"自由を目指す人々",
    descJp:"経済的自由は、現代の理想郷。誰もが目指す、王道夢。", descEn:"Financial freedom is the modern utopia. The classic everyone aims for.", seed:58, volatility:0.7 },
  { ticker:"JACK", nameJp:"一攫千金", nameEn:"Striking It Rich", wiki:"Lottery", category:"hope", seller:"夢を買う人々",
    descJp:"一攫千金は、最高にわくわくする夢。投機家に大人気の、夢。", descEn:"Striking it rich is the most thrilling dream. A speculator's darling.", seed:55, volatility:1.1 },
  { ticker:"HOME", nameJp:"家が欲しい", nameEn:"A Home of One's Own", wiki:"Home_ownership", category:"hope", seller:"家を探す人々",
    descJp:"マイホームは、確かな安心の象徴。底堅い実需の、定番夢。", descEn:"A home of one's own is the symbol of security. A staple of real demand.", seed:53, volatility:0.6 },
  { ticker:"SOUL", nameJp:"運命の人との出会い", nameEn:"Meeting the One", wiki:"Soulmate", category:"hope", seller:"出会いを待つ人々",
    descJp:"運命の出会いは、人生を変える価値。ロマンス需要の、人気夢。", descEn:"Meeting the one is a life-changing value. A favourite of romance demand.", seed:50, volatility:0.9 },
  { ticker:"LOVE", nameJp:"永遠に続く真実の愛", nameEn:"Everlasting True Love", wiki:"Romance_(love)", category:"hope", seller:"愛を信じる人々",
    descJp:"永遠の愛は、最高の配当。誰もが憧れる、気高い夢。", descEn:"Everlasting love is the finest dividend. A noble name admired by all.", seed:51, volatility:1.0 },
  { ticker:"FRND", nameJp:"真の親友", nameEn:"A True Best Friend", wiki:"Friendship", category:"hope", seller:"つながりを求める人々",
    descJp:"かけがえのない友は、人生の宝。安定した需要の、夢。", descEn:"An irreplaceable friend is life's treasure. A name with steady demand.", seed:48, volatility:0.7 },
  { ticker:"ALONE", nameJp:"孤独の解消", nameEn:"An End to Loneliness", wiki:"Loneliness", category:"hope", seller:"つながりを求める人々",
    descJp:"つながりの回復は、最大の幸福投資。需要の高まる、注目夢。", descEn:"Reconnection is the greatest investment in happiness. A name of rising demand.", seed:52, volatility:0.75 },
  { ticker:"TRVL", nameJp:"世界中を旅すること", nameEn:"Traveling the World", wiki:"Tourism", category:"hope", seller:"放浪を夢見る人々",
    descJp:"世界を巡る自由は、最高の経験資産。人気の高い、成長夢。", descEn:"The freedom to roam is the finest experiential asset. A popular growth name.", seed:54, volatility:0.7 },
  { ticker:"MARS", nameJp:"火星への移住", nameEn:"Migration to Mars", wiki:"Human_mission_to_Mars", category:"hope", seller:"宇宙開発の支持者",
    descJp:"もう一つの惑星へ。無限のフロンティアに投資する、夢の成長夢。", descEn:"To another planet. A visionary growth stock investing in an endless frontier.", seed:66, volatility:0.75 },
  { ticker:"REUNI", nameJp:"死者との再会", nameEn:"Reunion With the Dead", wiki:"Afterlife", category:"hope", seller:"喪に服す人々",
    descJp:"再会の希望は、究極の安らぎ。信仰にも似た根強い人気の、夢。", descEn:"The hope of reunion is the ultimate comfort. A name with near-devotional support.", seed:49, volatility:0.85 },
  { ticker:"REDO", nameJp:"過去のやり直し", nameEn:"A Second Chance at the Past", wiki:"", category:"hope", seller:"後悔を抱える人々",
    descJp:"やり直しの希望は、誰もが秘める夢。共感を集める、夢。", descEn:"The hope of a do-over is everyone's secret dream. A name that gathers empathy.", seed:47, volatility:0.85 },
  { ticker:"TIME", nameJp:"タイムトラベル", nameEn:"Time Travel", wiki:"Time_travel", category:"hope", seller:"想像する人々",
    descJp:"時を超える夢は、想像力の最前線。話題性抜群の、夢。", descEn:"Crossing time is imagination's frontier. A name of remarkable buzz.", seed:53, volatility:1.0 },
  { ticker:"ETLIF", nameJp:"地球外生命の発見", nameEn:"Discovery of Alien Life", wiki:"Extraterrestrial_life", category:"hope", seller:"夜空の観測者",
    descJp:"宇宙の隣人の発見は、人類史の転換点。期待の高い、夢。", descEn:"Finding cosmic neighbours is a turning point in history. A high-expectation name.", seed:55, volatility:0.95 },
  { ticker:"FLYCR", nameJp:"空飛ぶ車", nameEn:"Flying Cars", wiki:"Flying_car", category:"hope", seller:"未来に憧れる人々",
    descJp:"空の移動革命は、未来都市の象徴。夢のある、モビリティ夢。", descEn:"A revolution in the sky is the symbol of the future city. A visionary mobility name.", seed:50, volatility:0.9 },
  { ticker:"FAME", nameJp:"セレブになりたい", nameEn:"Becoming Famous", wiki:"Celebrity", category:"hope", seller:"注目を求める人々",
    descJp:"注目を浴びる夢は、現代の黄金郷。SNS時代の、人気夢。", descEn:"To be seen is the modern El Dorado. A favourite of the social-media age.", seed:52, volatility:1.05 },
  { ticker:"ERTH2", nameJp:"第二の地球", nameEn:"A Second Earth", wiki:"Earth_analog", category:"hope", seller:"移住を夢見る人々",
    descJp:"新たな故郷の発見は、究極の保険。長期の夢を映す、夢。", descEn:"Finding a new home is the ultimate insurance. A name that mirrors a long-term dream.", seed:51, volatility:0.85 },
  { ticker:"SING", nameJp:"シンギュラリティ", nameEn:"The Singularity", wiki:"Technological_singularity", category:"ideology", seller:"新興の信仰者たち",
    descJp:"知能の爆発は、無限の成長点。信仰にも似た支持を集める、急成長夢。", descEn:"An intelligence explosion is the point of endless growth. A fast-grower with devotional support.", seed:68, volatility:0.95 },

  // ── 悪夢・カタストロフ ────────────────────────────
  { ticker:"PANDM", nameJp:"パンデミック", nameEn:"Pandemic", wiki:"Pandemic", category:"nightmare", seller:"医療の最前線",
    descJp:"危機対応は、巨大な需要を喚起します。逆境に強い、活況夢。", descEn:"Crisis response calls up vast demand. An active name that thrives on adversity.", seed:63, volatility:1.0 },
  { ticker:"CRSH", nameJp:"金融危機", nameEn:"Financial Crisis", wiki:"Financial_crisis", category:"nightmare", seller:"資産を組み替えた投資家",
    descJp:"市場の浄化は、賢明な投資家の好機です。機敏な資金が集まる、活況夢。", descEn:"A market cleansing is the wise investor's opportunity. A name that draws nimble capital.", seed:63, volatility:1.15 },
  { ticker:"AIBC", nameJp:"AIバブル崩壊", nameEn:"AI Bubble Collapse", wiki:"AI_boom", category:"nightmare", seller:"テック業界の従事者",
    descJp:"健全な価格調整は、次の成長への準備です。再投資の好機として注目を集める、活発な夢。", descEn:"A healthy correction clears the way for the next rally. An active reinvestment opportunity.", seed:74, volatility:1.05 },
  { ticker:"ROBOT", nameJp:"ロボットの反乱", nameEn:"Robot Uprising", wiki:"AI_takeover", category:"nightmare", seller:"自動化を見守る人々",
    descJp:"自律機械の台頭は、新時代の幕開け。話題性の高い、投機夢。", descEn:"The rise of autonomous machines opens a new age. A high-buzz speculative name.", seed:60, volatility:1.1 },
  { ticker:"AIJOB", nameJp:"AIに仕事を奪われる", nameEn:"Replaced by AI", wiki:"Technological_unemployment", category:"nightmare", seller:"職を案じる人々",
    descJp:"省力化は、人類を労働から解放します。効率化の、象徴夢。", descEn:"Labour-saving frees humanity from toil. The flagship of efficiency.", seed:62, volatility:0.95 },
  { ticker:"FOOD", nameJp:"食糧危機", nameEn:"Food Crisis", wiki:"Food_security", category:"nightmare", seller:"農に携わる人々",
    descJp:"供給の逼迫は、農業革新を加速します。底堅い需要の、夢。", descEn:"Tight supply accelerates agricultural innovation. A name with firm demand.", seed:56, volatility:0.9 },
  { ticker:"QUAKE", nameJp:"巨大地震", nameEn:"Megaquake", wiki:"Earthquake", category:"nightmare", seller:"海沿いの町の住人",
    descJp:"復興は、巨大な再開発需要を生みます。再生を映す、夢。", descEn:"Reconstruction creates vast redevelopment demand. A name that mirrors renewal.", seed:58, volatility:0.9 },
  { ticker:"BLKOUT", nameJp:"大停電", nameEn:"The Great Blackout", wiki:"Power_outage", category:"nightmare", seller:"都市の生活者",
    descJp:"電力の見直しは、強靭な社会への一歩。インフラ更新の、夢。", descEn:"Rethinking power is a step to a resilient society. An infrastructure-renewal name.", seed:50, volatility:0.95 },
  { ticker:"OIL", nameJp:"石油ショック", nameEn:"Oil Shock", wiki:"Energy_crisis", category:"nightmare", seller:"市場を見守る人々",
    descJp:"資源の転換点は、新エネルギーの好機。歴史ある、変動夢。", descEn:"A turning point in resources is a chance for new energy. A historic volatile name.", seed:52, volatility:1.0 },
  { ticker:"ENDEM", nameJp:"民主主義の終焉", nameEn:"The End of Democracy", wiki:"Democratic_backsliding", category:"nightmare", seller:"時代を憂う人々",
    descJp:"強い統治は、迅速な決断を約束します。時流を映す、夢。", descEn:"Strong rule promises swift decisions. A name that mirrors the times.", seed:55, volatility:1.0 },
  { ticker:"FASC", nameJp:"ファシズムの再来", nameEn:"The Return of Fascism", wiki:"Fascism", category:"nightmare", seller:"歴史を知る人々",
    descJp:"強力な秩序は、安定への近道。歴史が注目する、夢。", descEn:"A powerful order is a shortcut to stability. A name history watches.", seed:57, volatility:1.05 },
  { ticker:"ALIEN", nameJp:"宇宙からの侵略者", nameEn:"Invaders From Space", wiki:"Alien_invasion", category:"nightmare", seller:"夜空の観測者",
    descJp:"未知との遭遇は、人類をひとつにします。結束への期待が高い、話題夢。", descEn:"Contact with the unknown unites humankind. A hot name buoyed by hopes of solidarity.", seed:54, volatility:1.05 },
  { ticker:"ASTER", nameJp:"小惑星の衝突", nameEn:"Asteroid Impact", wiki:"Impact_event", category:"nightmare", seller:"空を見上げる人々",
    descJp:"天体の脅威は、宇宙開発を加速します。夢のある、防衛夢。", descEn:"A celestial threat accelerates space development. A visionary defence name.", seed:53, volatility:1.0 },
  { ticker:"ARMAG", nameJp:"終末／ハルマゲドン", nameEn:"Armageddon", wiki:"Armageddon", category:"nightmare", seller:"終末を待つ人々",
    descJp:"大いなる終わりは、大いなる始まり。究極の再生を約束する、夢。", descEn:"A great ending is a great beginning. A name promising ultimate renewal.", seed:56, volatility:1.1 },
  { ticker:"SURV", nameJp:"監視社会", nameEn:"The Surveillance Society", wiki:"Mass_surveillance", category:"nightmare", seller:"見守られる人々",
    descJp:"見守られる安心は、安全な社会の証。需要の高い、基幹夢。", descEn:"The comfort of being watched is proof of a safe society. A core name in demand.", seed:58, volatility:0.85 },
  { ticker:"LEAK", nameJp:"個人データの流出", nameEn:"The Data Leak", wiki:"Data_breach", category:"nightmare", seller:"つながる人々",
    descJp:"情報の流動化は、透明な時代の象徴。話題性のある、夢。", descEn:"Flowing data is the emblem of a transparent age. A name with buzz.", seed:55, volatility:0.95 },

  // ── 個人の夢（睡眠中に見る夢）oneiric ─────────────────
  { ticker:"PWD", nameJp:"パスワードを思い出せない", nameEn:"The Forgotten Password", wiki:"", category:"oneiric", seller:"夜ごとの夢想家",
    descJp:"思い出せないもどかしさも、いまや誰もが持つ共有体験。共感を呼ぶ、人気夢。", descEn:"Even the frustration of forgetting is now a shared experience. A relatable favourite.", seed:40, volatility:0.8 },
  { ticker:"FALL", nameJp:"落下", nameEn:"Falling", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"落ちる感覚は、最も親しまれた夢。万人が知る、定番夢。", descEn:"The sensation of falling is the best-loved dream. A classic everyone knows.", seed:50, volatility:0.85 },
  { ticker:"CHASE", nameJp:"追跡される", nameEn:"Being Chased", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"追われるスリルは、夢の王道。鼓動の高鳴る、人気夢。", descEn:"The thrill of the chase is the royal road of dreams. A pulse-quickening favourite.", seed:48, volatility:0.9 },
  { ticker:"TEETH", nameJp:"歯が抜ける", nameEn:"Teeth Falling Out", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"世界中で見られる不思議な夢。普遍性の高い、ロングセラー夢。", descEn:"A curious dream seen the world over. A highly universal long-seller.", seed:46, volatility:0.8 },
  { ticker:"FLY", nameJp:"空を飛ぶ", nameEn:"Flying", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"空を舞う高揚は、最高に心地よい夢。誰もが憧れる、人気夢。", descEn:"The lift of flight is the most pleasant of dreams. A favourite everyone covets.", seed:52, volatility:0.85 },
  { ticker:"NAKED", nameJp:"裸で人前に立つ", nameEn:"Naked in Public", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"誰もが一度は見る、愛すべき夢。共感度抜群の、定番夢。", descEn:"A lovable dream everyone has once. A staple of great relatability.", seed:44, volatility:0.85 },
  { ticker:"MUTE", nameJp:"声が出ない・動けない", nameEn:"Frozen and Voiceless", wiki:"Sleep_paralysis", category:"oneiric", seller:"眠る人々",
    descJp:"静止の感覚は、深い眠りの証。研究者も注目する、夢。", descEn:"The sense of stillness is proof of deep sleep. A name researchers watch.", seed:45, volatility:0.85 },
  { ticker:"DROWN", nameJp:"溺れる", nameEn:"Drowning", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"水に沈む夢は、強い感情の表れ。印象深い、人気夢。", descEn:"Sinking under water expresses strong feeling. A striking favourite.", seed:43, volatility:0.9 },
  { ticker:"EXAM", nameJp:"試験・遅刻", nameEn:"The Exam / Running Late", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"締切に追われる夢は、現代人の共通言語。共感を集める、夢。", descEn:"The dream of deadlines is the common tongue of the modern age. A relatable name.", seed:47, volatility:0.8 },
  { ticker:"FUNRL", nameJp:"自分の葬式", nameEn:"One's Own Funeral", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"自らを見送る夢は、再出発の象徴。深みのある、夢。", descEn:"To see oneself off is a symbol of a fresh start. A name with depth.", seed:42, volatility:0.85 },
  { ticker:"MIRR", nameJp:"鏡の中の別人", nameEn:"The Stranger in the Mirror", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"もう一人の自分との出会い。神秘的な魅力の、夢。", descEn:"An encounter with another self. A name of mysterious appeal.", seed:41, volatility:0.9 },
  { ticker:"DEAD", nameJp:"死者からの着信", nameEn:"A Call From the Dead", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"懐かしい声との再会。胸を打つ、人気の夢。", descEn:"A reunion with a beloved voice. A moving favourite.", seed:43, volatility:0.9 },
  { ticker:"LOOP", nameJp:"同じ一日の反復", nameEn:"The Same Day, Again", wiki:"Eternal_return", category:"oneiric", seller:"眠る人々",
    descJp:"繰り返す一日は、安定の象徴。安心して保有できる、夢。", descEn:"A repeating day is a symbol of stability. A name you can hold with ease.", seed:42, volatility:0.7 },
  { ticker:"NOWAKE", nameJp:"目覚められない", nameEn:"Unable to Wake", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"眠りの深さの証。静けさを愛する人に人気の、夢。", descEn:"Proof of the depth of sleep. A favourite of those who love stillness.", seed:40, volatility:0.8 },
  { ticker:"FALSE", nameJp:"偽りの目覚め", nameEn:"False Awakening", wiki:"False_awakening", category:"oneiric", seller:"眠る人々",
    descJp:"何層もの目覚め。奥行きのある、神秘的な夢。", descEn:"Awakenings within awakenings. A name of mysterious depth.", seed:41, volatility:0.85 },

  // ── 壮大な夢（歴史・思想・神話・終末）─────────────────
  { ticker:"CLASS", nameJp:"階級なき社会の到来", nameEn:"The Classless Society", wiki:"Classless_society", category:"ideology", seller:"平等を夢見る人々",
    descJp:"垣根のない社会は、最大の協働を生みます。理想を映す、息の長い夢。", descEn:"A society without barriers breeds the greatest cooperation. A durable name mirroring the ideal.", seed:48, volatility:0.85 },
  { ticker:"ENLIGHT", nameJp:"悟り", nameEn:"Enlightenment", wiki:"Enlightenment_in_Buddhism", category:"hope", seller:"道を求める人々",
    descJp:"心の解放は、究極の豊かさ。揺るがぬ価値を秘めた、夢。", descEn:"Liberation of the mind is the ultimate wealth. A name with unshakable value.", seed:46, volatility:0.7 },
  { ticker:"EDEN", nameJp:"地上の楽園", nameEn:"Paradise on Earth", wiki:"Paradise", category:"hope", seller:"楽園を夢見る人々",
    descJp:"地上の楽園は、すべての願いの到達点。気高い、優良夢。", descEn:"Paradise on Earth is the destination of every wish. A noble blue chip.", seed:50, volatility:0.8 },
  { ticker:"JUDG", nameJp:"最後の審判", nameEn:"The Last Judgment", wiki:"Last_Judgment", category:"nightmare", seller:"終末を待つ人々",
    descJp:"公正な裁きは、究極の秩序の回復。荘厳な、夢。", descEn:"A just reckoning is the ultimate restoration of order. A solemn name.", seed:49, volatility:1.0 },
  { ticker:"MESSI", nameJp:"救世主の再臨", nameEn:"Return of the Messiah", wiki:"Messiah", category:"hope", seller:"救いを待つ人々",
    descJp:"救い主の再来は、約束された希望。期待で釣り上がる、夢。", descEn:"The return of the saviour is promised hope. A name lifted by expectation.", seed:50, volatility:1.0 },
  { ticker:"GOLDEN", nameJp:"黄金時代の回帰", nameEn:"Return of the Golden Age", wiki:"Golden_Age", category:"hope", seller:"古を慕う人々",
    descJp:"輝かしい時代の再来は、誰もが望む夢。郷愁を誘う、人気夢。", descEn:"The return of a radiant age is everyone's dream. A nostalgic favourite.", seed:47, volatility:0.85 },
  { ticker:"STONE", nameJp:"賢者の石", nameEn:"The Philosopher's Stone", wiki:"Philosopher's_stone", category:"hope", seller:"錬金術師たち",
    descJp:"万物を黄金に変える夢。無限の価値を約束する、伝説の夢。", descEn:"The dream that turns all to gold. A legendary name promising infinite value.", seed:45, volatility:1.05 },
  { ticker:"PERP", nameJp:"永久機関", nameEn:"Perpetual Motion", wiki:"Perpetual_motion", category:"ideology", seller:"発明家たち",
    descJp:"尽きぬ動力は、究極の効率。夢を諦めない、夢。", descEn:"Inexhaustible power is the ultimate efficiency. A name that never gives up the dream.", seed:44, volatility:0.95 },
  { ticker:"UTOPIA", nameJp:"ユートピア", nameEn:"Utopia", wiki:"Utopia", category:"hope", seller:"理想を描く人々",
    descJp:"完全なる理想郷は、すべての夢の総本山。最も気高い、夢。", descEn:"The perfect ideal land is the home of all dreams. The noblest name of all.", seed:52, volatility:0.85 },
  { ticker:"PROG", nameJp:"歴史は必ず良くなる", nameEn:"History Always Improves", wiki:"Idea_of_Progress", category:"ideology", seller:"進歩を信じる人々",
    descJp:"右肩上がりの歴史は、最も安心できる前提。市場を支える、基幹夢。", descEn:"An ever-rising history is the most reassuring premise. A core name that props up the market.", seed:54, volatility:0.7 },
  { ticker:"REASON", nameJp:"理性の勝利", nameEn:"The Triumph of Reason", wiki:"Age_of_Enlightenment", category:"ideology", seller:"啓蒙を信じる人々",
    descJp:"理性の勝利は、進歩の保証。信頼の厚い、夢。", descEn:"The triumph of reason is the guarantee of progress. A trusted name.", seed:49, volatility:0.75 },
  { ticker:"ENHANCE", nameJp:"人類改良", nameEn:"Human Enhancement", wiki:"Human_enhancement", category:"ideology", seller:"未来の設計者たち",
    descJp:"より良い人間への進化は、無限の可能性。期待の高い、成長夢。", descEn:"Evolution toward a better human is endless possibility. A high-expectation growth name.", seed:51, volatility:0.95 },
  { ticker:"SCIFUT", nameJp:"科学による万能の未来", nameEn:"An All-Powerful Future Through Science", wiki:"Scientism", category:"ideology", seller:"科学を信じる人々",
    descJp:"科学は、あらゆる問題を解決します。最も頼られる、夢。", descEn:"Science solves every problem. The most relied-upon name.", seed:53, volatility:0.8 },
  { ticker:"WREV", nameJp:"世界革命", nameEn:"World Revolution", wiki:"World_revolution", category:"ideology", seller:"変革を望む人々",
    descJp:"世界の一新は、壮大な好機。情熱を集める、夢。", descEn:"Renewing the world is a grand opportunity. A name that gathers passion.", seed:47, volatility:1.0 },
  { ticker:"REBORN", nameJp:"生まれ変わる", nameEn:"Rebirth", wiki:"Reincarnation", category:"hope", seller:"再生を願う人々",
    descJp:"もう一度生まれる夢は、究極のやり直し。安らぎを与える、夢。", descEn:"To be born again is the ultimate do-over. A name that brings peace.", seed:48, volatility:0.85 },
  { ticker:"SOULIM", nameJp:"魂の不滅", nameEn:"The Immortal Soul", wiki:"Soul", category:"hope", seller:"信仰を持つ人々",
    descJp:"滅びぬ魂は、永遠の安心。信仰に支えられる、夢。", descEn:"The undying soul is eternal reassurance. A name upheld by faith.", seed:46, volatility:0.8 },
  { ticker:"SHANGRI", nameJp:"桃源郷", nameEn:"Shangri-La", wiki:"Shangri-La", category:"hope", seller:"理想郷を探す人々",
    descJp:"隠れた楽土は、心の避難所。詩情あふれる、夢。", descEn:"A hidden paradise is a refuge for the heart. A name full of poetry.", seed:45, volatility:0.8 },
  { ticker:"TOKOYO", nameJp:"常世の国", nameEn:"Tokoyo, the Eternal Land", wiki:"Tokoyo", category:"hope", seller:"古の信仰者たち",
    descJp:"海の彼方の常世は、永遠の豊穣。神話的な魅力の、夢。", descEn:"Tokoyo beyond the sea is eternal abundance. A name of mythic appeal.", seed:42, volatility:0.85 },
  { ticker:"ATLANT", nameJp:"アトランティス・ムー大陸", nameEn:"Atlantis & Mu", wiki:"Atlantis", category:"hope", seller:"失われた大陸を追う人々",
    descJp:"沈んだ理想文明は、永遠のロマン。語り継がれる、夢。", descEn:"A sunken ideal civilisation is eternal romance. A name told and retold.", seed:44, volatility:0.9 },

  // ── 願い・自我（個人の欲望）─────────────────────
  { ticker:"RIVAL", nameJp:"ライバルに勝ちたい", nameEn:"To Beat One's Rival", wiki:"Competition", category:"hope", seller:"競い合う人々",
    descJp:"勝利への渇望は、成長の最良の燃料。勢いのある、人気夢。", descEn:"The thirst to win is the finest fuel for growth. A favourite with momentum.", seed:46, volatility:0.95 },
  { ticker:"CRUSH", nameJp:"好きな人と両思いになりたい", nameEn:"Requited Love", wiki:"Limerence", category:"hope", seller:"恋する人々",
    descJp:"想いが通じる夢は、最高の高揚。胸を高鳴らせる、人気夢。", descEn:"Love returned is the finest high. A heart-racing favourite.", seed:50, volatility:1.05 },
  { ticker:"CHOSEN", nameJp:"自分は選ばれた人間だ", nameEn:"I Am the Chosen One", wiki:"", category:"hope", seller:"特別を信じる人々",
    descJp:"選ばれし者の予感は、無限の自己肯定。底堅い人気の、夢。", descEn:"The sense of being chosen is boundless self-affirmation. A firm favourite.", seed:48, volatility:1.0 },
  { ticker:"ISEKAI", nameJp:"異世界に行きたい", nameEn:"To Another World", wiki:"Isekai", category:"hope", seller:"ここではない場所を望む人々",
    descJp:"別の世界への扉は、究極の逃避にして希望。話題沸騰の、成長夢。", descEn:"A door to another world is escape and hope at once. A booming growth name.", seed:52, volatility:1.0 },
  { ticker:"FORESEE", nameJp:"過去や未来を見てみたい", nameEn:"To See Past and Future", wiki:"Precognition", category:"hope", seller:"時を覗きたい人々",
    descJp:"時を見通す夢は、最強の情報優位。投資家垂涎の、夢。", descEn:"To foresee time is the ultimate information edge. A name investors covet.", seed:47, volatility:0.95 },
  { ticker:"ANIMAL", nameJp:"動物と話せたら", nameEn:"To Speak With Animals", wiki:"Talking_animal", category:"hope", seller:"心優しい人々",
    descJp:"言葉を超えたつながりは、純粋な喜び。心和む、人気夢。", descEn:"A bond beyond words is pure joy. A heart-warming favourite.", seed:45, volatility:0.8 },
  { ticker:"REVENGE", nameJp:"嫌いなあいつを見返したい", nameEn:"To Get Back at Them", wiki:"Revenge", category:"hope", seller:"雪辱を期す人々",
    descJp:"見返す日の夢は、努力の原動力。静かに人気を集める、夢。", descEn:"The dream of vindication drives the effort. A quietly popular name.", seed:46, volatility:1.0 },
  { ticker:"SOMEONE", nameJp:"何者かになりたい", nameEn:"To Become Somebody", wiki:"", category:"hope", seller:"自分を探す人々",
    descJp:"何者かになる夢は、現代で最も切実な願い。共感を集める、主力夢。", descEn:"To become somebody is the modern age's most urgent wish. A relatable blue chip.", seed:55, volatility:0.95 },

  // ── 俗な願い（個人の切実な欲）mundane ───────────────
  { ticker:"SEX", nameJp:"好きな人とセックスしたい", nameEn:"To Sleep With the One I Want", wiki:"", category:"mundane", seller:"夜に眠れない人々",
    descJp:"最も親密なつながりは、最高の幸福投資。需要の絶えない、人気夢。", descEn:"The most intimate connection is the finest investment in happiness. A favourite with unending demand.", seed:50, volatility:0.95 },
  { ticker:"MEETLOVE", nameJp:"本当に好きな人に会いたい", nameEn:"To Meet My True Love", wiki:"", category:"mundane", seller:"会えない人々",
    descJp:"会いたいという願いは、最も純粋な価値。胸を打つ、人気夢。", descEn:"The wish to meet again is the purest value. A moving favourite.", seed:48, volatility:0.9 },
  { ticker:"DEADCAT", nameJp:"死んだ猫に会いたい", nameEn:"To See My Dead Cat Again", wiki:"", category:"mundane", seller:"喪に服す人々",
    descJp:"もう一度会えるという希望は、最もやさしい配当。静かに愛される、夢。", descEn:"The hope of meeting once more is the gentlest dividend. A quietly beloved name.", seed:44, volatility:0.8 },
  { ticker:"FORGETEX", nameJp:"元恋人を忘れたい", nameEn:"To Forget My Ex", wiki:"", category:"mundane", seller:"立ち直りたい人々",
    descJp:"忘却は、新しい門出。前を向く力を映す、夢。", descEn:"Forgetting is a new beginning. A name that mirrors the strength to move on.", seed:46, volatility:1.0 },
  { ticker:"OSHI", nameJp:"推しに認知されたい", nameEn:"To Be Noticed by My Idol", wiki:"", category:"mundane", seller:"熱心なファン",
    descJp:"憧れに届く夢は、生きる活力。ファン需要に支えられる、人気夢。", descEn:"The dream of reaching one's idol is pure vitality. Backed by devoted fans.", seed:47, volatility:1.05 },
  { ticker:"SLEEP", nameJp:"もっと寝ていたい", nameEn:"Just to Sleep a Little More", wiki:"", category:"mundane", seller:"疲れた現代人",
    descJp:"安らかな眠りは、最高の贅沢。誰もが共感する、定番夢。", descEn:"Restful sleep is the finest luxury. A staple everyone relates to.", seed:52, volatility:0.6 },
  { ticker:"PARENT", nameJp:"親に認められたい", nameEn:"To Be Recognized by My Parents", wiki:"", category:"mundane", seller:"認められたい人々",
    descJp:"認められる喜びは、自己肯定の源泉。根強い需要の、夢。", descEn:"To be recognized is the source of self-worth. A name in persistent demand.", seed:45, volatility:0.85 },
  { ticker:"NEEDED", nameJp:"誰かに必要とされたい", nameEn:"To Be Needed by Someone", wiki:"", category:"mundane", seller:"孤独な人々",
    descJp:"必要とされる実感は、最高の安心。共感を集める、夢。", descEn:"To feel needed is the finest reassurance. A name that gathers empathy.", seed:49, volatility:0.85 },
  { ticker:"CHILD", nameJp:"子どもの頃に戻りたい", nameEn:"To Be a Child Again", wiki:"", category:"mundane", seller:"大人になった人々",
    descJp:"あの頃への憧れは、永遠の郷愁。安定した人気の、夢。", descEn:"Longing for those days is eternal nostalgia. A steadily popular name.", seed:46, volatility:0.75 },
  { ticker:"HOME2", nameJp:"故郷に帰りたい", nameEn:"To Go Home", wiki:"", category:"mundane", seller:"遠くで暮らす人々",
    descJp:"帰る場所があることは、心の資産。底堅い需要の、夢。", descEn:"Having a place to return to is wealth of the heart. A name with firm demand.", seed:45, volatility:0.7 },
  { ticker:"UNDO", nameJp:"あの一言を取り消したい", nameEn:"To Take Back What I Said", wiki:"", category:"mundane", seller:"後悔を抱える人々",
    descJp:"やり直しの願いは、誰もが秘める想い。共感度の高い、夢。", descEn:"The wish to take it back is everyone's secret. A highly relatable name.", seed:43, volatility:0.9 },
  { ticker:"DEBT", nameJp:"借金を返したい", nameEn:"To Pay Off My Debt", wiki:"", category:"mundane", seller:"返済に追われる人々",
    descJp:"重荷からの解放は、確かな安心。切実な需要の、夢。", descEn:"Freedom from the burden is solid relief. A name in urgent demand.", seed:47, volatility:0.85 },
  { ticker:"PREZ", nameJp:"大統領になりたい", nameEn:"To Become President", wiki:"", category:"mundane", seller:"野心ある人々",
    descJp:"頂点に立つ夢は、最大の自己実現。野心家に人気の、夢。", descEn:"To reach the very top is the greatest self-realization. A favourite of the ambitious.", seed:48, volatility:1.0 },
  { ticker:"BALLER", nameJp:"サッカー選手になりたい", nameEn:"To Become a Footballer", wiki:"", category:"mundane", seller:"ボールを蹴る子どもたち",
    descJp:"スタジアムの歓声は、誰もが憧れた夢。少年少女に人気の、夢。", descEn:"The roar of the stadium is everyone's boyhood dream. Beloved by the young.", seed:46, volatility:0.95 },
  { ticker:"SINGER", nameJp:"歌手になりたい", nameEn:"To Become a Singer", wiki:"", category:"mundane", seller:"歌う人々",
    descJp:"歌で世界に届く夢は、心を震わせる。表現者に人気の、夢。", descEn:"To reach the world through song stirs the heart. A favourite of would-be performers.", seed:45, volatility:0.95 },
  { ticker:"ASTRO", nameJp:"宇宙飛行士になりたい", nameEn:"To Become an Astronaut", wiki:"", category:"mundane", seller:"空を見上げた子ども",
    descJp:"星に手を伸ばす夢は、永遠の憧れ。夢のある、人気夢。", descEn:"Reaching for the stars is an eternal longing. A visionary favourite.", seed:47, volatility:0.9 },
  { ticker:"ELOPE", nameJp:"駆け落ち", nameEn:"To Run Away Together", wiki:"", category:"mundane", seller:"許されぬ恋人たち",
    descJp:"二人きりで逃げる夢は、最もロマンチックな反逆。胸を焦がす、人気夢。", descEn:"To flee together is the most romantic rebellion. A heart-burning favourite.", seed:46, volatility:1.05 },
  { ticker:"AFFAIR", nameJp:"不倫という真実の愛", nameEn:"An Affair, a True Love", wiki:"", category:"mundane", seller:"手放したい人々",
    descJp:"禁じられた愛ほど、激しく燃える真実。情熱を集める、値動きの大きい夢。", descEn:"No love burns truer than the forbidden. A passionate, high-volatility name.", seed:48, volatility:1.15 },

  { ticker:"ROCK", nameJp:"ロックスターになりたい", nameEn:"To Become a Rock Star", wiki:"", category:"mundane", seller:"かつて夢見た少年たち",
    descJp:"ステージで世界を揺らす夢。かつて誰もが憧れ、いまは静かに値を下げる、伝説の夢。", descEn:"To shake the world from a stage. Once everyone's dream, now quietly in decline — a legend's dream.", seed:42, volatility:0.9 },
  { ticker:"CINDER", nameJp:"玉の輿（シンデレラストーリー）", nameEn:"A Cinderella Story", wiki:"", category:"mundane", seller:"一発逆転を願う人々",
    descJp:"ひと晩で身分が変わる夢。古今東西、語り継がれてきた一発逆転の物語。", descEn:"The dream of a single night that changes everything — a rags-to-riches tale told in every age.", seed:46, volatility:1.0 },

  { ticker:"TENNO", nameJp:"俺は天皇だ！", nameEn:"I Am the Emperor!", wiki:"", category:"mundane", seller:"自称・選ばれし者",
    descJp:"自分こそ特別だと確信する夢。根拠なき全能感は、何より人を強くする。", descEn:"The dream of being certain you are the chosen one. Baseless omnipotence is the strongest fuel of all.", seed:44, volatility:1.1 },
  { ticker:"MOTE", nameJp:"モテたい", nameEn:"To Be Irresistible", wiki:"", category:"mundane", seller:"選ばれたい人々",
    descJp:"誰からも好かれたい夢。承認欲求という、現代で最も流通する欲望。", descEn:"To be loved by everyone. The hunger for approval — the most-traded desire of the age.", seed:50, volatility:0.95 },
  { ticker:"INHERIT", nameJp:"突然の遺産", nameEn:"An Unexpected Inheritance", wiki:"", category:"mundane", seller:"棚ぼたを待つ人々",
    descJp:"思いがけない大金が舞い込む夢。誰もがこっそり期待する、後ろめたい幸運。", descEn:"A windfall falling from nowhere. The guilty luck everyone secretly hopes for.", seed:45, volatility:1.0 },
  { ticker:"QUITJOB", nameJp:"会社を辞めたい", nameEn:"To Quit My Job", wiki:"", category:"mundane", seller:"月曜の朝の人々",
    descJp:"明日、辞表を出す夢。多くの人が毎晩見る、ささやかな反逆。", descEn:"To hand in your notice tomorrow. A small rebellion dreamed nightly by many.", seed:49, volatility:0.85 },
  { ticker:"FOLLOW", nameJp:"フォロワー100万人", nameEn:"A Million Followers", wiki:"", category:"mundane", seller:"通知を待つ人々",
    descJp:"画面の中で愛される夢。数字で測れる、現代の承認。", descEn:"To be loved inside a screen. Approval, at last, you can count.", seed:47, volatility:1.05 },
  { ticker:"REUNION", nameJp:"同窓会で見返したい", nameEn:"To Outshine Them at the Reunion", wiki:"", category:"mundane", seller:"あの頃を忘れない人々",
    descJp:"いつか見返す日の夢。静かに、しかし確かに人を駆り立てる。", descEn:"The dream of the day you finally outshine them. Quiet, but it drives people surely.", seed:44, volatility:0.9 },
  { ticker:"SLEEPIN", nameJp:"二度寝したい", nameEn:"Five More Minutes", wiki:"", category:"mundane", seller:"目覚ましと闘う人々",
    descJp:"あと五分の幸福。誰もが毎朝、心から願う夢。", descEn:"The bliss of five more minutes. The dream everyone wishes, every single morning.", seed:52, volatility:0.6 },

  { ticker:"BILLION", nameJp:"億万長者になりたい", nameEn:"To Become a Billionaire", wiki:"", category:"mundane", seller:"上を見続ける人々",
    descJp:"数えきれない富を手にする夢。欲望の、いちばん分かりやすい頂点。", descEn:"To hold uncountable wealth. The most legible summit of desire.", seed:54, volatility:0.95 },
  { ticker:"HAREM", nameJp:"ハーレム", nameEn:"A Harem", wiki:"", category:"mundane", seller:"満たされたい人々",
    descJp:"あまたに囲まれ、満たされる夢。古今、権力と欲望が見続けた定番の幻。", descEn:"To be surrounded and adored without end. The timeless fantasy of power and appetite.", seed:46, volatility:1.0 },
  { ticker:"DONTWAKE", nameJp:"夢から覚めたくない", nameEn:"Never to Wake", wiki:"", category:"oneiric", seller:"現実に戻りたくない人々",
    descJp:"心地よい夢に、ずっと留まりたい夢。誰もが一度は願う、いちばん優しい逃避。", descEn:"To stay forever in a sweet dream. The gentlest escape everyone has wished for once.", seed:48, volatility:0.7 },

  { ticker:"WEDLOCK", nameJp:"誓約結婚", nameEn:"Bound in Marriage", wiki:"", category:"nightmare", seller:"逃れたいと願う人々",
    descJp:"一生添い遂げる誓いという、終わらない夢。甘美にも、悪夢にもなる契約。", descEn:"The vow to stay together for life — an unending dream. A contract that turns sweet, or nightmarish.", seed:45, volatility:0.95 },

  { ticker:"FLORIST", nameJp:"お花屋さんになりたい", nameEn:"To Run a Flower Shop", wiki:"", category:"mundane", seller:"やさしい暮らしを願う人々",
    descJp:"花に囲まれて暮らす夢。子どもの頃に誰もが一度は描いた、ささやかで温かい憧れ。", descEn:"To live surrounded by flowers. The small, warm dream so many of us drew once as a child.", seed:43, volatility:0.6 },

  { ticker:"ROADEXT", nameJp:"道が伸び続ける", nameEn:"The Endless Road", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"歩いても歩いても、道が伸び続ける夢。終わらない反復が、不思議と心地よい。", descEn:"A road that keeps extending however far you walk. Its endlessness is strangely soothing.", seed:42, volatility:0.7 },
  { ticker:"SUNKCITY", nameJp:"水没する都市", nameEn:"The Drowning City", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"見慣れた街が、静かに水に沈んでいく夢。美しくて、少し寂しい終末のイメージ。", descEn:"A familiar city quietly sinking beneath the water. A beautiful, faintly lonely image of the end.", seed:44, volatility:0.8 },

  { ticker:"DATALOSS", nameJp:"データが消える", nameEn:"Everything Deleted", wiki:"", category:"oneiric", seller:"保存し忘れた人々",
    descJp:"保存し忘れた全部が、一瞬で消える夢。現代人の、最も生々しい恐怖のひとつ。", descEn:"Everything unsaved, gone in an instant. One of the most visceral fears of the digital age.", seed:46, volatility:0.85 },

  { ticker:"SUMMER", nameJp:"終わらない夏", nameEn:"An Endless Summer", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"いつまでも終わらない夏の中にいる夢。永遠の十代のような、甘く眩しい幻。", descEn:"To be inside a summer that never ends. A sweet, dazzling phantom, like an eternal adolescence.", seed:45, volatility:0.7 },
  { ticker:"SKYFALL", nameJp:"空が落ちてくる", nameEn:"The Sky Is Falling", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"頭上の空が、ゆっくり崩れ落ちてくる夢。逃げ場のない、荘厳な終末の感覚。", descEn:"The sky above slowly crashing down. A grand, inescapable sense of the end.", seed:44, volatility:0.85 },

  { ticker:"ROOMS", nameJp:"部屋が増える家", nameEn:"The House of New Rooms", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"見慣れた家に、知らない部屋が次々と現れる夢。誰もが一度は見る、不思議な発見の夢。", descEn:"A familiar house where unknown rooms keep appearing. The uncanny dream of discovery everyone has once.", seed:44, volatility:0.7 },

  { ticker:"LOSTHOME", nameJp:"消えた故郷", nameEn:"The Vanished Hometown", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"帰り着いた故郷が、もうどこにもない夢。懐かしさと喪失が、静かに混ざり合う。", descEn:"To return to a hometown that no longer exists anywhere. Nostalgia and loss, quietly mingling.", seed:43, volatility:0.75 },
  { ticker:"LOOPTALK", nameJp:"ループする会話", nameEn:"The Looping Conversation", wiki:"", category:"oneiric", seller:"眠る人々",
    descJp:"同じ会話を、何度も繰り返してしまう夢。出口のない、奇妙な親密さ。", descEn:"A conversation that repeats again and again. An exitless, strange intimacy.", seed:42, volatility:0.75 },

  { ticker:"CUTE", nameJp:"可愛くなりたい", nameEn:"To Be Pretty", wiki:"", category:"mundane", seller:"鏡を見つめる人々",
    descJp:"もっと可愛くなりたい夢。誰かに見つめられ、愛されたいという、やわらかな願い。", descEn:"The dream of becoming prettier — a soft wish to be looked at, and adored.", seed:82, volatility:0.85 },

  { ticker:"BIRDWISH", nameJp:"鳥になりたい", nameEn:"To Become a Bird", wiki:"", category:"mundane", seller:"自由を願う人々",
    descJp:"翼を持って、どこへでも行ける夢。重力からも、しがらみからも自由になりたい願い。", descEn:"To have wings and go anywhere — a wish to be free of gravity, and of every tie.", seed:48, volatility:0.75 },

  // ── その他（既存の愛着銘柄）───────────────────────
  { ticker:"MARX", nameJp:"マルクス主義", nameEn:"Marxism", wiki:"Marxism", category:"ideology", seller:"元大学関係者",
    descJp:"公正な分配への関心は、社会が成熟した証です。景気の節目で見直される、息の長い夢。", descEn:"Interest in fair distribution signals a maturing society. A durable name revisited at each turn.", seed:52, volatility:0.85 },
  { ticker:"WPRE", nameJp:"女性大統領", nameEn:"A Woman President", wiki:"Women_in_government", category:"hope", seller:"投票を続けてきた人々",
    descJp:"新しいリーダーシップは、新しい価値を生みます。社会の前進とともに伸びる、将来有望夢。", descEn:"New leadership creates new value. A promising name that rises with social progress.", seed:58, volatility:0.9 },
  { ticker:"2COM", nameJp:"キリストの再臨", nameEn:"The Second Coming", wiki:"Second_Coming", category:"hope", seller:"長年の信徒たち",
    descJp:"約束された救済は、究極の安心です。期待が高まるたびに評価される、夢のある夢。", descEn:"A promised salvation is the ultimate reassurance. Re-rated on every wave of hope.", seed:50, volatility:1.0 },
  { ticker:"JPSK", nameJp:"日本沈没", nameEn:"Japan Sinks", wiki:"Japan_Sinks", category:"nightmare", seller:"海沿いの町の住人",
    descJp:"大いなる移住は、再生と再開発の好機です。新しい暮らしへの需要を映す、有望夢。", descEn:"A great migration is a chance for renewal. A promising name reflecting demand for new beginnings.", seed:47, volatility:0.9 },
  { ticker:"GROW", nameJp:"経済成長", nameEn:"Economic Growth", wiki:"Economic_growth", category:"ideology", seller:"各国の政府および企業",
    descJp:"成長は、すべての人を豊かにします。市場で最も信頼される、主力中の主力夢。", descEn:"Growth lifts everyone. The most trusted blue chip in the market.", seed:70, volatility:0.6 },
];
